In [11]:
#Abbiamo una lista di liste: 
mat = [[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]] 
#Che tipo di struttura dati o matematica potrebbe rappresentare? UNA MATRICE
#Notare che tutte le liste "interne" sono della stessa dimensione 
#Come facciamo per accedere ad un elemento in particolare?

# mat[indice riga][indice colonna]
print(mat[0][0])  
print(mat[1][3])  
print(mat[2][4])
print(mat[1][0])  

0
8
14
5


In [20]:
#Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial().
#e la variabile .pi la riconoscete?
import math
print(math.sin(60))
print(math.cos(60))
print(math.factorial(10))

print(math.pi)

-0.3048106211022167
-0.9524129804151563
3628800
3.141592653589793


In [23]:
#Proviamo a eseguire math.degrees(math.pi) 
#Qual è e cosa significa il risultato? 
#Per saperne di più su questa funzione possiamo usare help(math.degrees)

print(math.degrees(math.pi))
help(math.degrees)

#math.degrees(math.pi) la funzione converte un angolo da radianti in gradi. Utilizzando pi greco come variabile otteniamo 180, poichè pi greco rappresenta 180° in radianti

180.0
Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [46]:
#L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
import numpy as np
#trasformiamola in un array NumPy 
lst = np.array(lst)  #casting

#e rispondiamo alle domande del CEO della Object SpA: 
#qual è stata la vendita massima mensile? E quella minima? 
vendita_massima =np.max(lst)
vendita_minima = np.min(lst)
print(vendita_massima)
print(vendita_minima)
#quali sono le vendite mensili maggiori di 4999 oggetti? 
vendite_maggiori = lst > 4999
print(vendite_maggiori)
print(lst[vendite_maggiori])
#E quante ne sono? 
print(vendite_maggiori.size)   #?
#quali sono le vendite minori di 3000 oggetti?
vendite_minori = lst < 3000
print(lst[vendite_minori])
print(len(vendite_minori))   #?

8150
1280
[False  True  True False False False False False  True  True  True  True]
[5500 7200 6410 8150 7100 5350]
12
[2000 1280 1900 2500]
12


In [ ]:
#Consideriamo il seguente dizionario: 
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} 
#Consideriamo ora la seguente Series: 
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], 
                             index=range(1997, 2005)) 
#Possiamo accedere alle stesse informazioni nello stesso modo: 
fatturati_dict[1997] 
fatturati_series[1997] 
#Dunque qual è la differenza tra i due tipi di dato? 
#            R:#Sulle series si possono effettuare operazioni matematiche rapide su tutti gli elementi, cosa che non dizionario è possibile solo con un ciclo
#Cosa potremmo fare con la Series che non possiamo fare con il dizionario?


In [49]:
#L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, 
#memorizzato in un ndarray: 
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: 
#con un ciclo for 
for stipendio in stipendi:
    stipendio_raddoppiato = stipendio*2
    print(stipendio_raddoppiato)

#con il masking
print(stipendi*2)

200
400
600
800
1000
1200
1400
1600
1800
2000
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
